config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :lamas do
    collection do
      get 'search'
    end
  end

  get 'home/index'
  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :lamas
end

app/models/lama.rb
class Lama < ApplicationRecord
  mount_uploader :cover, CoverUploader

  searchable do
    text :title, :description

    integer :category_id
  end
  # extend FriendlyId
  # friendly_id :title, use: [:slugged, :finders]

  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @lamas    = @category.lamas.decorate
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @lamas = Lama.all.decorate
    @max_dicsount = Lama.maximum(:discount_value)
  end
end

app/controllers/lamas_controller.rb
class LamasController < ApplicationController
  def search
    @lamas = Lama.search do
      fulltext params[:q]

      with :category_id, params[:category_id]
    end.result
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.container
  .row
    .col-sm-3.sidebar
      .bg-white.shadow
        .widget-menu
          .cat-text
            input.form-control placeholder=('Искать купоны') type="text" /
          ul.nav.sidebar-nav
            li.dropdown
              a.ripple-effect.dropdown-toggle data-toggle="dropdown" href="#"
                i.ti-shine
                | Travel
                span.sidebar-badge
                  | 12
                b.caret
              ul.dropdown-menu
                li
                  a href="#" tabindex="-1"
                    | Europe
                    span.sidebar-badge
                      | 12
            li
              a href="#"
                i.ti-gift
                | Gifts
                span.sidebar-badge
                  | 3
            li
              a href="#"
                i.ti-shopping-cart
                | Products
                span.sidebar-badge
                  | 456
            li
              a href="#"
                i.ti-ticket
                | Tickets
                span.sidebar-badge.badge-circle
                  | 12
            li
              a href="#"
                i.ti-pulse
                | Health
                span.sidebar-badge.badge-circle
                  | 45
            li
              a href="#"
                i.ti-direction-alt
                | Things To Do
                span.sidebar-badge.badge-circle
                  | 117
            li
              a href="#"
                i.ti-cut
                | Fashion
                span.sidebar-badge.badge-circle
                  | 117
            li
              a href="#"
                i.ti-music-alt
                | Fun Stuff
                span.sidebar-badge.badge-circle
                  | 117
            li
              a href="#"
                i.ti-harddrives
                | Electronics
                span.sidebar-badge.badge-circle
                  | 117
    .col-sm-9
      .slider
        .row
          #grid-slider.flexslider
            ul.slides
              - @lamas.each do |lama|
                = render partial: 'lamas/big_item', locals: { lama: lama }

section#page.container
  .shadow.bg-white.mTop-30.frameLR
    .row
      .col-md-3.col-sm-4
        .l-element
          .box-icon
            .icon-wrap
              i.ti-target
            .text
              h4
                | Find Your Deal
              p
                | Find perfect offer
      .col-md-3.col-sm-4
        .l-element
          .box-icon
            .icon-wrap
              i.ti-shopping-cart
            .text
              h4
                | Buy Deal
              p
                | Buy or save your deal
      /! /.icon box
      .col-md-3.col-sm-4
        .l-element
          .box-icon
            .icon-wrap
              i.fa.fa-smile-o
            .text
              h4
                = "Скидки до #{@max_dicsount}%"
              p
                | Сохраняйте десятки рублей с нами!

      .col-md-3.col-sm-4
        .l-element
          .box-icon
            .icon-wrap
              i.ti-star
            .text
              h4
                | Круглосуточная поддержка
              p
                | +375 (29) 170-18-10

  .mTop-30
    .row
      .col-sm-12.clearfix
        .hr-link
          hr.mBtm-50 data-symbol=('FEATURED DEALS') /
          .view-all
            a href="index.html"
              | VIEW ALL
    .row
      - 6.times do
        = render partial: 'lamas/small_item'

  .no-class
    .row
      .col-sm-12.clearfix
        .hr-link
          hr.mBtm-50 data-symbol=('LATEST DEALS') /
          .view-all
            a href="index.html"
              | VIEW ALL
    .row
      .col-sm-3
        .deal-entry.orange
          .image
            a href="#" target="_blank" title="#"
              img.img-responsive alt="#" src="http://placehold.it/700x420" /
            span.bought
              i.ti-tag
              | 169
          /! /.image
          .title
            a href="#" target="_blank" title=('ATLETIKA 3 mēnešu abonements')
              | 3-dnevni oddih za 2 v hotelu Ferienhotel Alber 4*
          .entry-content
            .prices.clearfix
              .procent
                | -65%
              .price
                i.ti-money
                b
                  | 60,00
              .old-price
                span
                  i.ti-money
                  | 171,00
            p
              | Immerse Yourself in the Magic of Cambodia with a Luxurious Eight Day/Seven Night Escape at Two of the World’s Finest Hotels!
          /! /.entry content
          footer.info_bar.clearfix
            ul.unstyled.list-inline.row
              li.time.col-sm-7.col-xs-6.col-lg-8
                i.ti-timer
                b
                  | 8
                | d.
                b
                  | 20
                | st.
                b
                  | 58
                | min.
              li.info_link.col-sm-5.col-xs-6.col-lg-4
                a.btn.btn-block.btn-default.btn-raised.btn-sm href="#"
                  | View Deal
      /! /.deal
      .col-sm-3
        .deal-entry.orange
          .image
            a href="#" target="_blank" title="#"
              img.img-responsive alt="#" src="http://placehold.it/700x420" /
            span.bought
              i.ti-tag
              | 169
          /! /.image
          .title
            a href="#" target="_blank" title=('ATLETIKA 3 mēnešu abonements')
              | 3-dnevni oddih za 2 v hotelu Ferienhotel Alber 4*
          .entry-content
            .prices.clearfix
              .procent
                | -65%
              .price
                i.ti-money
                b
                  | 60,00
              .old-price
                span
                  i.ti-money
                  | 171,00
            p
              | Immerse Yourself in the Magic of Cambodia with a Luxurious Eight Day/Seven Night Escape at Two of the World’s Finest Hotels!
          /! /.entry content
          footer.info_bar.clearfix
            ul.unstyled.list-inline.row
              li.time.col-sm-7.col-xs-6.col-lg-8
                i.ti-timer
                b
                  | 8
                | d.
                b
                  | 20
                | st.
                b
                  | 58
                | min.
              li.info_link.col-sm-5.col-xs-6.col-lg-4
                a.btn.btn-block.btn-default.btn-raised.btn-sm href="#"
                  | View Deal
      /! /.deal
      .col-sm-3
        .deal-entry.orange
          .image
            a href="#" target="_blank" title="#"
              img.img-responsive alt="#" src="http://placehold.it/700x420" /
            span.bought
              i.ti-tag
              | 169
          /! /.image
          .title
            a href="#" target="_blank" title=('ATLETIKA 3 mēnešu abonements')
              | 3-dnevni oddih za 2 v hotelu Ferienhotel Alber 4*
          .entry-content
            .prices.clearfix
              .procent
                | -65%
              .price
                i.ti-money
                b
                  | 60,00
              .old-price
                span
                  i.ti-money
                  | 171,00
            p
              | Immerse Yourself in the Magic of Cambodia with a Luxurious Eight Day/Seven Night Escape at Two of the World’s Finest Hotels!
          /! /.entry content
          footer.info_bar.clearfix
            ul.unstyled.list-inline.row
              li.time.col-sm-7.col-xs-6.col-lg-8
                i.ti-timer
                b
                  | 8
                | d.
                b
                  | 20
                | st.
                b
                  | 58
                | min.
              li.info_link.col-sm-5.col-xs-6.col-lg-4
                a.btn.btn-block.btn-default.btn-raised.btn-sm href="#"
                  | View Deal
      /! /.deal
      .col-sm-3
        .deal-entry.orange
          .image
            a href="#" target="_blank" title="#"
              img.img-responsive alt="#" src="http://placehold.it/700x420" /
            span.bought
              i.ti-tag
              | 169
          /! /.image
          .title
            a href="#" target="_blank" title=('ATLETIKA 3 mēnešu abonements')
              | 3-dnevni oddih za 2 v hotelu Ferienhotel Alber 4*
          .entry-content
            .prices.clearfix
              .procent
                | -65%
              .price
                i.ti-money
                b
                  | 60,00
              .old-price
                span
                  i.ti-money
                  | 171,00
            p
              | Immerse Yourself in the Magic of Cambodia with a Luxurious Eight Day/Seven Night Escape at Two of the World’s Finest Hotels!
          /! /.entry content
          footer.info_bar.clearfix
            ul.unstyled.list-inline.row
              li.time.col-sm-7.col-xs-6.col-lg-8
                i.ti-timer
                b
                  | 8
                | d.
                b
                  | 20
                | st.
                b
                  | 58
                | min.
              li.info_link.col-sm-5.col-xs-6.col-lg-4
                a.btn.btn-block.btn-default.btn-raised.btn-sm href="#"
                  | View Deal
/! /.row
/! /.frame
/! /#page ends
.cta-box.clearfix
  .container
    .row
      .col-md-3.col-sm-3.col-xs-12.pull-right
        a.btn.btn-raised.btn-danger.ripple-effect.btn-lg data-original-title="" href="#" title=""
          i.ti-shopping-cart
          | \&nbsp; Sumbit Deal
      .col-md-9.col-sm-9.col-xs-12
        h3
          | Welcome to Kupon. Responsive Deal Template
        p
          | Carefully designed to bring you the best performance, usage and customization experience!
/! /.CTA

app/views/lamas/_big_item.html.slim
li
  .col-sm-7.col-lg-7.omega
    article.bg-image.entry-lg data-image-src="#{lama.cover}"
    /= "http://placehold.it/900x600"
    .deal-short-entry
      p.lead
        = lama.title
  .col-sm-5.col-lg-5.alpha.entry-lg
    .buyPanel.animated.fadeInLeft.bg-white.Aligner.shadow
      .content
        .deal-content
          h3
            | Sirenis Punta Cana Resort Casino
          p
            = lama.title
        ul.deal-price.list-unstyled.list-inline
          li.price
            h3
              = lama.price
          li.buy-now
            = link_to 'Купить!', lama_path(lama), class: 'btn btn-danger btn-lg btn-raised ripple-effect'
        .dealAttributes
          .valueInfo.bg-light.shadow
            .value
              p.value
                = lama.price
              p.text
                | Цена
            .discount
              p.value
                = lama.signed_discount_value
              p.text
                | Скидка
            .save
              p.value
                = lama.savings
              p.text
                | Сохраняете
          /! /.value info
          .timeLeft.text-center
            p
              | Hurry up Only a few deals left
            span.time
              i.ti-timer.color-green
              b
                | 8
              | d.
              b
                | 20
              | st.
              b
                | 58
              | min.
          ul.statistic.list-unstyled.list-inline
            li
              p
                i.ti-user
                b
                  | for 2
                | Person
            li
              i.ti-tag
              b
                | 169
              | Bought
            li
              i.ti-face-smile
              | Offer success
          .social-sharing.text-center data-permalink="http://labs.carsonshold.com/social-sharing-buttons"
            /! https://developers.facebook.com/docs/plugins/share-button/
            a.share-facebook href="http://www.facebook.com/sharer.php?u=http://themeforest.net/user/codenpixel" target="_blank"
              span.icon.icon-facebook
              span.share-title
                | Share
              span.share-count.is-loaded 288
            /! https://dev.twitter.com/docs/intents
            a.share-twitter href="http://twitter.com/share?url=http://themeforest.net/user/codenpixel" target="_blank"
              span.icon.icon-twitter
              span.share-title
                | Tweet
              span.share-count.is-loaded 78
/li
/  .col-sm-7.col-lg-7.omega
/    article.bg-image.entry-lg data-image-src="http://placehold.it/900x600"
/      .deal-short-entry
/        p
/          | Kingscliff: From $349 for a 3-Night Romantic Stay with Bottle of Wine...
/  .col-sm-5.col-lg-5.alpha.entry-lg
/    .buyPanel.animated.fadeInLeft.bg-white.bordered.Aligner
/      .content
/        .deal-content
/          h3
/            | Riviera Maya All-Inclusive Cities 5*
/          p
/            | Kingscliff: From $349 for a 3-Night Romantic Stay with Bottle of Wine...
/        ul.deal-price.list-unstyled.list-inline
/          li.price
/            h3
/              | $999
/          li.buy-now
/            a.btn.btn-primary.btn-raised.ripple-effect
/              | BUY NOW
/        .dealAttributes
/          .valueInfo.bg-light.shadow
/            .value
/              p.value
/                | $2,475
/              p.text
/                | Value
/            .discount
/              p.value
/                | 59%
/              p.text
/                | Discount
/            .save
/              p.value
/                | $1,476
/              p.text
/                | SAVINGS
/          /! /.value info
/          .timeLeft.text-center
/            p
/              | Hurry up Only a few deals left
/            span.time
/              i.ti-timer.color-green
/              b
/                | 8
/              | d.
/              b
/                | 20
/              | st.
/              b
/                | 58
/              | min.
/          ul.statistic.list-unstyled.list-inline
/            li
/              p
/                i.ti-users
/                b
/                  | for 2
/                | Person
/            li
/              i.ti-tag
/              b
/                | 169
/              | Bought
/            li
/              i.ti-face-smile
/              | Offer success
/          .social-sharing.text-center data-permalink="http://labs.carsonshold.com/social-sharing-buttons"
/            /! https://developers.facebook.com/docs/plugins/share-button/
/            a.share-facebook href="http://www.facebook.com/sharer.php?u=http://themeforest.net/user/codenpixel" target="_blank"
/              span.icon.icon-facebook
/              span.share-title
/                | Share
/              span.share-count.is-loaded 288
/            /! https://dev.twitter.com/docs/intents
/            a.share-twitter href="http://twitter.com/share?url=http://themeforest.net/user/codenpixel" target="_blank"
/              span.icon.icon-twitter
/              span.share-title
/                | Tweet
/              span.share-count.is-loaded 78

app/views/lamas/_small_item.html.slim
.col-sm-4
  .deal-entry.orange
    .image
      a href="#" target="_blank" title="#"
        img.img-responsive alt="#" src="http://placehold.it/700x420" /
      span.bought
        i.ti-tag
        | 169
    /! /.image
    .title
      a href="#" target="_blank" title=('ATLETIKA 3 mēnešu abonements')
        | 3-dnevni oddih za 2 v hotelu Ferienhotel Alber 4*
    .entry-content
      .prices.clearfix
        .procent
          | -65%
        .price
          i.ti-money
          b
            | 60,00
        .old-price
          span
            i.ti-money
            | 171,00
      p
        | Immerse Yourself in the Magic of Cambodia with a Luxurious Eight Day/Seven Night Escape at Two of the World’s Finest Hotels!
    /! /.entry content
    footer.info_bar.clearfix
      ul.unstyled.list-inline.row
        li.time.col-sm-7.col-xs-6.col-lg-8
          i.ti-timer
          b
            | 8
          | d.
          b
            | 20
          | st.
          b
            | 58
          | min.
        li.info_link.col-sm-5.col-xs-6.col-lg-4
          a.btn.btn-block.btn-default.btn-raised.btn-sm href="#"
            | View Deal

app/views/lamas/search.html.slim
= render partial: 'shared/search_result', locals: { lamas: @lamas }

app/views/layouts/application.html.slim
doctype html
html.gr__pamukovic_com lang="en"
  head
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

    meta content=('text/html; charset=UTF-8') http-equiv="content-type" /
    meta charset="utf-8" /
    title
      | Find your Lama
    meta content="#" name="generator" /
    meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport" /
    link href="/assets/bootstrap.min.css" rel="stylesheet" /
    link href="/assets/themify-icons.css" rel="stylesheet" /
    link href="/assets/font-awesome.css" rel="stylesheet" /
    link href="/assets/owl.carousel.css" rel="stylesheet" /
    link href="/assets/animate.min.css" rel="stylesheet" /
    link href="/assets/animsition.css" rel="stylesheet" /
    link href="/assets/plugins.min.css" rel="stylesheet" /
    link href="/assets/style.css" rel="stylesheet" /
    /![if lt IE 9]
      | <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script
    link href="#" rel=('shortcut icon') /
    link href="#" rel="apple-touch-icon" /
    link href="#" rel="apple-touch-icon" sizes="72x72" /
    link href="#" rel="apple-touch-icon" sizes="114x114" /

  body
    .site-wrapper.animsition data-animsition-in="fade-in" data-animsition-out="fade-out"
      = render partial: 'shared/header'
      = yield
      = render partial: 'shared/footer'

app/views/shared/_footer.html.slim
footer#footer
  .container
    .col-sm-4
      img.img-responsive.logo alt="#" src="images/logo-dark.png" /
      p
        | Kupon,travel deals &amp; publishing,with minimal design. We provide you with the latest fresh inspiration straight from the industrie.
    .col-sm-4
      h5
        | COMMON TAGS
      ul.tags
        li
          a.tag href="#"
            | Vacation
        li
          a.tag href="#"
            | Rentals
        li
          a.tag href="#"
            | Deals
        li
          a.tag href="#"
            | Travel deals
        li
          a.tag href="#"
            | Vacation deals
        li
          a.tag href="#"
            | Adriatic coast
        li
          a.tag href="#"
            | Europe
        li
          a.tag href="#"
            | Island
    .col-sm-2
      h5
        | CATEGORIES
      ul.list-unstyled
        li
          | Vacation Deals
        li
          | Online Deals
        li
          | Digital goods
        li
          | Travel Deals
        li
          | Hotel deals
        li
          | Featured
        li
          | All Categories ..
    .col-sm-2
      h5
        | ABOUT US
      ul.list-unstyled
        li
          | Available Jobs
        li
          | Sumbit Deal
        li
          | Contact Us
        li
          | History
        li
          | Impressium
  .btmFooter
    .container
      .col-sm-7
        p
          strong
            | Copyright 2017
          | Trade deals
          i.ti-heart
          strong
            | by LamasTeam
      .col-sm-5
        ul.pay-opt.pull-right.list-inline.list-unstyled
          li
            a href="#" title="#"
              img.img-responsive alt="" src="/assets/amz-icon.png" /
          li
            a href="#" title="#"
              img.img-responsive alt="" src="/assets/paypal-icon.png" /
          li
            a href="#" title="#"
              img.img-responsive alt="" src="/assets/ax-icon.png" /
          li
            a href="#" title="#"
              img.img-responsive alt="" src="/assets/mb-icon.png" /
          li
            a href="#" title="#"
              img.img-responsive alt="" src="/assets/mst-icon.png" /
          li
            a href="#" title="#"
              img.img-responsive alt="" src="/assets/mstr-icon.png" /

  script src="/assets/jquery.min.js"
  script src="/assets/kupon.js"
  script src="/assets/bootstrap.min.js"
  script src="/assets/jquery.animsition.min.js"
  script src="/assets/owl.carousel.js"
  script src="/assets/jquery.flexslider-min.js"
  script src="/assets/plugins.js"

app/views/shared/_header.html.slim
header
  .top-bar.bg-light.hdden-xs
    .container
      .row
        .col-sm-6.list-inline.list-unstyled.no-margin.hidden-xs
          p.no-margin
            | Есть вопросы?
            strong
              | +375 29 1701810
            | or artemshut@gmail.com
        .pull-right.col-sm-6
          ul.list-inline.list-unstyled.pull-right
            li.active
              a href="#"
                i.ti-cart
                | Faq
            li
              = link_to 'Войти', new_user_session_path
            li
              = link_to 'Регистрация', new_user_registration_path
            li
              a href="#"
                i.ti-shopping-cart
                | Корзина
  .header
    .container
      .row
        .col-sm-3
          a.navbar-brand.logo href="index.html"
            img.img-responsive alt="" src="images/logo.png"
        .col-sm-9
          = form_tag search_lamas_path, method: 'get', class: 'search-form', id: 'search_form' do
            .col-sm-4
              .row
                .col-md-12
                  = text_field_tag :q, params[:q], placeholder: 'Поиск лучших предложений'
            .col-sm-4
              = select_tag(:category_id, options_for_select(Category.all.map { |category| [category.name, category.id] }), selected: params[:category_id], prompt: 'Выберите категорию')
              /select.form-control
                option selected="selected" value="0"
                  | Выберите категорию
                - Category.all.each do |category|
                  option value="#{category.id}"
                    = category.name
            .col-sm-4
              = link_to 'Искать', '#', onclick: "$('#search_form').submit()", class: 'btn btn-raised ripple-effect btn-default btn-block'
  #nav-wrap
    .nav-wrap-holder
      #nav_wrapper.container
        nav#main_navbar.navbar.navbar-static-top.nav-white role="navigation"
          .navbar-header
            button.navbar-toggle data-target="#Navbar" data-toggle="collapse" type="button"
              span.sr-only
                | Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
          #Navbar.collapse.navbar-collapse
            /! regular link
            ul.nav.navbar-nav.navbar-left
              li
                a href="#{root_path}"
                  i.ti-home
                  | Главная
              li.dropdown
                a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button"
                  i.ti-clipboard
                  | Pages
                  span.caret
                ul.dropdown-menu role="menu"
                  li
                    a href="details_2.html"
                      | Deal Page 1
                  li
                    a href="details.html"
                      | Deal Page 2
                  li
                    a href="results.html"
                      | Search Results
                  li
                    a href="contact.html"
                      | Contact
                  li
                    a href="faq.html"
                      | FAQ page
                  li
                    a href="sumbit.html"
                      | Sumbit deal
                  li
                    a href="registration.html"
                      | Registration
                  li
                    a href="cart.html"
                      | Cart Page
                  li
                    a href="checkout.html"
                      | Checkout
                  li
                    a href="features.html"
                      | Shortcodes
              li
                a href="results.html"
                  i.ti-list-ol
                  | Categories
              li
                a href="sumbit.html"
                  i.ti-settings
                  | Sumbit
              li
                a href="contact.html"
                  i.ti-email
                  | Contact

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>